In [264]:
import numpy as np

In [265]:
h = float(input("Ingrese valor a h: "))

Ingrese valor a h: 1


In [266]:

Tf = 10 # Temperatura en ptos (x,4,z)
g = 0.5 
ka = 0.5 # Conductividad

i = 0
j = 0
k = 0

# Número de puntos sin considerar caras exteriores en eje Y
p_alto = p_ancho = int((2/h)+1)
p_largo = int((4/h)+1)
print("p_alto : ", p_alto) # Puntos eje z
print("p_ancho:", p_ancho) # Puntos eje x
print("p_largo:", p_largo) # Puntos eje y

eje_medio_y = ((p_largo//2)+1)


print ("Eje medio y: ",eje_medio_y)

print(type(p_alto))

p_alto :  3
p_ancho: 3
p_largo: 5
Eje medio y:  3
<class 'int'>


In [267]:
def num_ec(h):
    """Esta funcion calcula la cantidad de ecuaciones que serán 
    necesarias para el sistema dependiendo del h entregado
    inicialmente
    Argumentos: h
    """
    nec = ((4/h)-1)*(((2/h)+1)**2)
    #print(nec)
    return nec

In [268]:
T = np.zeros((p_alto,p_ancho,p_largo))
print(T)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [269]:
def traslado_Matriz(T):
    """
    Esta función permite trasladar la Matriz T de 3 dimensiones a la matriz
    M_r (Matriz con los coeficientes)
    """
    global con_x
    global con_y 
    global M_r
    
    for i in range(0,p_ancho):
        for j in range(1,p_largo-1):
            for k in range(0,p_alto):
                M_r[con_x][con_y]=T[k][i][j]
                con_x += 1
    con_y += 1
    con_x = 0
    

In [273]:

def llenado_matriz_3d(i,j,k,avance_v_r):
    """
    Permite llenar la matriz de 3 dimensiones con los coeficientes del sistema
    """
    global T
    
    if j<eje_medio_y:
        Q = 0
    else:
        Q = 1
    
    r = (-Q/ka)*(h**2)
    
    if (i < p_ancho):
        if (i+1) != p_ancho:
            T[k][i+1][j] = 1
    
    if (j < p_largo-1):
        T[k][i][j+1] = 1
    else:
        r = r - 10
        
    if (k < p_alto):
        if (k+1)!=p_alto:
            T[k+1][i][j] = 1
    
    T[k][i][j] = -6
    
    if (i > 0):
        T[k][i-1][j] = 1
        
    if (j > 0):
        if j==1:
            T[k][i][j] = T[k][i][j]+1
            r = r + 0.5*h
        else:
            T[k][i][j-1] = 1
 
    
    if (k > 0):
        T[k-1][i][j] = 1 
        
    V_r[avance_v_r] = r 
    
    traslado_Matriz(T)
    
    T = np.zeros((p_alto,p_ancho,p_largo))


### Main

In [276]:
con_x = 0
con_y = 0

avance_v_r = 0
n_ec = int(num_ec(h))

M_r = [[0 for f in range(n_ec)] for g in range(n_ec)] 
V_r = np.zeros(n_ec) 

for i in range(0,p_ancho):
    for j in range(1,p_largo-1):
        for k in range(0,p_alto):
            llenado_matriz_3d(i,j,k,avance_v_r)
            avance_v_r += 1
            
#print (V_r)
#print(M_r)

Resultado = np.linalg.solve(M_r,V_r)
print("Resultados: ",Resultado)

Resultados:  [-0.13593063 -0.15608087 -0.13593063  0.13250861  0.17160216  0.13250861
  0.58777795  0.69707955  0.58777795 -0.15608087 -0.18014528 -0.15608087
  0.17160216  0.2235971   0.17160216  0.69707955  0.83531921  0.69707955
 -0.13593063 -0.15608087 -0.13593063  0.13250861  0.17160216  0.13250861
  0.58777795  0.69707955  0.58777795]
